name: MERN CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted # you can also use ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install & Build Frontend
      - name: Install frontend dependencies
        run: |
          cd client
          npm ci
          npm run build

      # Install Backend Dependencies
      - name: Install backend dependencies
        run: |
          cd server
          npm ci

  
      # # Optional: Deploy to EC2
      # - name: Deploy to EC2
      #   if: github.ref == 'refs/heads/main'
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd /var/www/mern-app
      #       git pull origin main
      #       cd client && npm run build
      #       cd ../server && npm install --legacy-peer-deps
      #       pm2 restart all
